# Generated by Django 4.2.9 on 2024-04-02 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Cajas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0002_alter_producto_existencia_en_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('F', 'Finalizado'), ('P', 'Pendiente')], default='A', max_length=1, verbose_name='Estado')),
                ('tipo_pago', models.CharField(max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibe_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cajas.cajas')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.cart')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('tipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.tipoventa')),
            ],
        ),
        migrations.CreateModel(
            name='VentasCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tiempo_cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_tiempo', models.CharField(max_length=100)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interes_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes_moratorio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mora_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_atraso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('productos', models.ManyToManyField(to='Productos.producto', verbose_name='productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='Productos.producto', verbose_name='productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(related_name='cart', through='Ventas.CartItem', to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
