# Generated by Django 4.2.9 on 2024-04-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_existencia_en_inventario'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(related_name='productos', through='Ventas.CartItem', to='Productos.producto'),
        ),
    ]
