# Generated by Django 4.2.9 on 2026-06-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_existencia_en_inventario'),
        ('Cajas', '0001_initial'),
        ('Clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0002_alter_cart_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='ticket_factura',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.ventas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cajas.cajas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.cart'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado',
            field=models.CharField(choices=[('F', 'Finalizado'), ('P', 'Pendiente'), ('A', 'Anulado')], default='F', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='recibe_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.tipoventa'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
