# version: '3'
# # implementacion con compose
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - DEBUG=0


version: '3'

services:
  web:
    build: .
    command: gunicorn volcanosm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"   # OJO: ahora usamos expose en vez de publicar al host
    environment:
      - DEBUG=0
