# Generated by Django 4.2.9 on 2024-01-12 15:31

import Configuraciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barra_Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.CharField(max_length=100)),
                ('numero_contacto', models.CharField(max_length=50)),
                ('url_facebook', models.CharField(max_length=100)),
                ('url_twitter', models.CharField(max_length=100)),
                ('url_linkedin', models.CharField(max_length=100)),
                ('url_instagram', models.CharField(max_length=100)),
                ('url_youtube', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarruselInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=Configuraciones.models.upload_to_carrusel_inicio)),
                ('url_boton', models.CharField(max_length=100)),
                ('texto_boton', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(help_text='Ingrese su dirección de correo electrónico', max_length=254, verbose_name='Correo electronico')),
                ('contact_phone', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_visible', models.BooleanField()),
                ('services_ico', models.ImageField(upload_to=Configuraciones.models.upload_to_services_bar)),
                ('services_ico_tag', models.CharField(max_length=150, null=True)),
                ('services_name', models.CharField(max_length=50)),
                ('services_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Team_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to=Configuraciones.models.upload_to_team_bar)),
                ('team_nombre', models.CharField(max_length=40)),
                ('team_job', models.CharField(max_length=30)),
                ('url_facebook', models.CharField(max_length=100)),
                ('url_twitter', models.CharField(max_length=100)),
                ('url_linkedin', models.CharField(max_length=100)),
                ('url_instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urls_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
