# Generated by Django 4.2.9 on 2024-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_bar',
            name='team_job',
            field=models.CharField(max_length=130),
        ),
    ]
