# Generated by Django 4.2.9 on 2024-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0004_urls_interes_alter_barra_principal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_largo', models.TextField()),
                ('titulo_corto', models.CharField(max_length=30)),
                ('medio_titulo', models.CharField(max_length=30)),
                ('descripcion_larga', models.TextField()),
                ('descripcion_corta', models.CharField(max_length=75)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'fecha_creacion',
            },
        ),
    ]
