# Generated by Django 4.2.9 on 2024-01-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0005_general_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_description',
            name='descripcion_larga',
            field=models.CharField(max_length=120),
        ),
    ]
