# Generated by Django 4.2.9 on 2024-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0006_alter_general_description_descripcion_larga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_description',
            name='descripcion_larga',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='general_description',
            name='titulo_largo',
            field=models.CharField(max_length=50),
        ),
    ]
