# Generated by Django 4.2.9 on 2024-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0007_alter_general_description_descripcion_larga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carruselinicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default="2024-02-03 16:12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carruselinicio',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='services_bar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default="2024-02-03 16:12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services_bar',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='team_bar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default="2024-02-03 16:12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_bar',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
