# Generated by Django 4.2.9 on 2024-02-07 17:11

import Configuraciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0008_carruselinicio_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to=Configuraciones.models.upload_to_direccionamiento)),
                ('url_azure', models.URLField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
