# Generated by Django 4.2.9 on 2024-11-15 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0010_wompi_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='wompi_config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
