# Generated by Django 4.2.9 on 2024-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0011_wompi_config_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wompi_config',
            options={'verbose_name': 'Configuración Wompi', 'verbose_name_plural': 'Configuraciones Wompi'},
        ),
        migrations.AlterField(
            model_name='wompi_config',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='wompi_config',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='wompi_config',
            name='cuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
