# Generated by Django 4.2.9 on 2024-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0013_alter_wompi_config_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wompi_config',
            name='client_id',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='wompi_config',
            name='client_secret',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
