# Generated by Django 4.2.9 on 2025-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0014_alter_wompi_config_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wompi_config',
            name='client_id',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='wompi_config',
            name='client_secret',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
