# Generated by Django 4.2.9 on 2026-06-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0002_alter_producto_existencia_en_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (compra/recepción)'), ('salida', 'Salida (venta)'), ('ajuste', 'Ajuste manual'), ('devolucion', 'Devolución (reingreso)')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Positivo suma stock, negativo resta')),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, help_text='Ej. Venta VL-0001', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Kardex',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
