# Generated by Django 4.2.9 on 2024-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_contacto',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
