# Generated by Django 4.2.9 on 2024-01-09 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerCabanias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad_personas', models.PositiveIntegerField()),
                ('costo_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comodidades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_personas', models.PositiveIntegerField()),
                ('costo_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienda_camping', models.BooleanField()),
                ('derecho_camping', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo_parqueo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_parqueo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.camping')),
            ],
        ),
    ]
