# Generated by Django 4.2.9 on 2024-01-31 00:20

import Servicios.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabanias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('descripcion1', models.TextField()),
                ('capacidad_personas', models.PositiveIntegerField()),
                ('costo_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.BooleanField(default=False)),
                ('incluye_cabania', models.TextField()),
                ('imagen', models.ImageField(upload_to='cabañas')),
            ],
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to=Servicios.models.icono_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesCabania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to=Servicios.models.imagen_cabania_upload_to)),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Cabaña',
            },
        ),
        migrations.CreateModel(
            name='ImagenesCamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to=Servicios.models.imagen_camping_upload_to)),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Cabaña',
            },
        ),
        migrations.CreateModel(
            name='ImagenesServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to=Servicios.models.imagen_servicio_upload_to)),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Cabaña',
            },
        ),
        migrations.CreateModel(
            name='Resena_cabanias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('cabania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='Servicios.cabanias')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=175)),
                ('imagen', models.ImageField(upload_to='servicios/{nombre}')),
                ('imagenes', models.ManyToManyField(null=True, to='Servicios.imagenesservicio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlquilerCabanias',
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='cantidad_adultos',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='cantidad_ninos',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='codigo_reserva',
            field=models.CharField(default=1, max_length=85, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='correo_electronico',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='direccion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='dui',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='pais_residencia',
            field=models.CharField(default='El Salvador', max_length=50),
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='precio_nino',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='qr_code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='tipo_documento',
            field=models.CharField(choices=[(' ', ' '), ('DUI', 'Documento Unico de Identidad'), ('CE', 'Cédula de extrangería'), ('LIC', 'Licencia Nacional'), ('PA', 'Pasaporte'), ('Otro', 'Otro')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamping',
            name='total_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservacamping',
            name='camping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.camping'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.tiposervicio'),
        ),
        migrations.AddField(
            model_name='cabanias',
            name='comodidades',
            field=models.ManyToManyField(to='Servicios.comodidad'),
        ),
        migrations.AddField(
            model_name='cabanias',
            name='imagenes',
            field=models.ManyToManyField(to='Servicios.imagenescabania'),
        ),
        migrations.AddField(
            model_name='cabanias',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.tiposervicio'),
        ),
        migrations.AddField(
            model_name='camping',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.tiposervicio'),
        ),
    ]
