# Generated by Django 4.2.9 on 2024-02-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_cabanias_comodidad_imagenescabania_imagenescamping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagenes',
            field=models.ManyToManyField(to='Servicios.imagenesservicio'),
        ),
    ]
