# Generated by Django 4.2.9 on 2024-02-04 15:45

import Servicios.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_alter_servicios_imagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesservicio',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagenesservicio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='imagenesservicio',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=Servicios.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=Servicios.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=Servicios.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=Servicios.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Servicios.servicios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='url_azure_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='url_azure_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='url_azure_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='url_azure_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicios',
            name='url_azure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cabanias',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cabanias',
            name='descripcion1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cabanias',
            name='incluye_cabania',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resena_cabanias',
            name='comentario',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reservacamping',
            name='direccion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
