# Generated by Django 4.2.9 on 2024-02-04 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_imagenesservicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
