# Generated by Django 4.2.9 on 2024-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_imagenesservicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='url_servicio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
