# Generated by Django 5.0.1 on 2024-01-09 05:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_alter_imagentour_options_remove_imagentour_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('dui', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('cantidad_adultos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_ninos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Tours.tour')),
            ],
        ),
    ]
