# Generated by Django 4.2.9 on 2024-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_reserva_qr_code_reserva_qr_code_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_nino',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='total_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
