# Generated by Django 4.2.9 on 2024-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_reserva_iva_reserva_precio_adulto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='precio_adulto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio_nino',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='precio',
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_nino',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
