# Generated by Django 4.2.9 on 2024-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0007_remove_reserva_precio_adulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='descripcion1',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='descripcion2',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='incluye_tour',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
