# Generated by Django 4.2.9 on 2024-01-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_tour_descripcion1_tour_descripcion2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_nino',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
