# Generated by Django 4.2.9 on 2024-01-09 22:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0009_reserva_precio_adulto_reserva_precio_nino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.13'), max_digits=5),
        ),
    ]
