# Generated by Django 4.2.9 on 2024-01-19 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0011_reserva_pais_residencia_reserva_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_ninos',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_documento',
            field=models.CharField(choices=[(' ', ' '), ('DUI', 'Documento Unico de Identidad'), ('CE', 'Cédula de extrangería'), ('LIC', 'Licencia Nacional'), ('PA', 'Pasaporte'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
