# Generated by Django 4.2.9 on 2024-01-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0012_alter_reserva_cantidad_ninos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='imagentour',
            name='imagen1',
            field=models.ImageField(default=1, upload_to='tours/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagentour',
            name='imagen2',
            field=models.ImageField(default=1, upload_to='tours/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagentour',
            name='imagen3',
            field=models.ImageField(default=1, upload_to='tours/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagentour',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Tours.tour'),
            preserve_default=False,
        ),
    ]
