# Generated by Django 4.2.9 on 2024-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0013_remove_tour_imagenes_imagentour_imagen1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(max_length=85, unique=True),
        ),
    ]
