# Generated by Django 4.2.9 on 2024-02-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0016_imagentour_url_azure_alter_imagentour_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagentour',
            old_name='url_azure',
            new_name='url_azure_1',
        ),
        migrations.AddField(
            model_name='imagentour',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
        migrations.AddField(
            model_name='imagentour',
            name='url_azure_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagentour',
            name='url_azure_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagentour',
            name='url_azure_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
    ]
