# Generated by Django 4.2.9 on 2024-02-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0017_rename_url_azure_imagentour_url_azure_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagentour',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='imagentour',
            name='url_azure_4',
        ),
    ]
