# Generated by Django 4.2.9 on 2024-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0018_remove_imagentour_imagen4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagentour',
            old_name='imagen',
            new_name='imagen4',
        ),
        migrations.AddField(
            model_name='imagentour',
            name='url_azure_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
