# Generated by Django 4.2.9 on 2024-02-01 03:28

import Tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0019_rename_imagen_imagentour_imagen4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagentour',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=Tours.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=Tours.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=Tours.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='imagentour',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=Tours.models.get_upload_path),
        ),
    ]
