# Generated by Django 4.2.9 on 2024-02-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0020_alter_imagentour_imagen1_alter_imagentour_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='url_azure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
