# Generated by Django 4.2.9 on 2024-02-04 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0021_tour_url_azure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='direccion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='incluye_tour',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
