# Generated by Django 4.2.9 on 2024-04-03 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0022_alter_resena_comentario_alter_reserva_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url_azure',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
