# Generated by Django 4.2.9 on 2024-02-05 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0022_alter_resena_comentario_alter_reserva_direccion_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tour',
        #     name='fecha_fin',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='tour',
        #     name='fecha_inicio',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='incluye_tour',
            field=models.TextField(),
        ),
    ]
