# Generated by Django 4.2.9 on 2024-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0023_tour_fecha_fin_tour_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='url_azure',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
