# Generated by Django 4.2.9 on 2024-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0023_tour_fecha_fin_tour_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[(' ', ' '), ('RESERVADO', 'Reserva realizada sin pago'), ('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Reserva pagada y realizada'), ('CANCELADO', 'Reserva Cancelada'), ('Otro', 'Otro')], default='RESERVADO', max_length=50),
        ),
    ]
