# Generated by Django 4.2.9 on 2024-02-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0023_tour_fecha_fin_tour_fecha_inicio_and_more'),
        ('Tours', '0024_alter_tour_url_azure'),
    ]

    operations = [
    ]
