# Generated by Django 4.2.9 on 2024-02-20 02:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0025_merge_20240215_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='incluye_tour',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
