# Generated by Django 4.2.9 on 2024-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0025_alter_reserva_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[(' ', ' '), ('RESERVADO', 'Reserva realizada sin pago'), ('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Reserva pagada y realizada'), ('CANCELADO', 'Reserva Cancelada'), ('Otro', 'Otro')], default='RESERVADO', max_length=50),
        ),
    ]
