# Generated by Django 4.2.9 on 2024-05-09 14:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0026_alter_reserva_estado_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacePagoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercio_id', models.CharField(max_length=500)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_producto', models.CharField(max_length=500)),
                ('url_qr_code', models.URLField()),
                ('url_enlace', models.URLField()),
                ('esta_productivo', models.BooleanField()),
                ('descripcionProducto', ckeditor.fields.RichTextField()),
                ('cantidad', models.CharField(max_length=5)),
                ('imagenProducto', models.URLField(max_length=250, null=True)),
                ('idEnlace', models.CharField(max_length=150)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlace_pago_set', to='Tours.reserva')),
            ],
        ),
    ]
