# Generated by Django 4.2.9 on 2025-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0028_tour_solo_finde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepagotour',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
