# Generated by Django 4.2.9 on 2024-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dui', models.CharField(max_length=10, verbose_name='DUI')),
                ('nit', models.IntegerField(verbose_name='NIT')),
                ('nombre_comercial', models.CharField(max_length=50, verbose_name='Nombre Comercial')),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
