# Generated by Django 4.2.9 on 2024-01-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlacepago',
            name='cantidad_maxima_cuotas',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='cantidad_maxima_pagos_exitosos',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='cantidad_maxima_pagos_fallidos',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='fecha_fin_vigencia',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='fecha_inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='permitir_pago_bitcoin',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='permitir_pago_cuotas_agricola',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='permitir_pago_punto_agricola',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='permitir_tarjeta_credito_debito',
        ),
        migrations.RemoveField(
            model_name='enlacepago',
            name='url_redirect',
        ),
    ]
