# Generated by Django 4.2.9 on 2024-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0003_remove_enlacepago_cantidad_por_defecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacepago',
            name='descripcionProducto',
            field=models.TextField(default='este es uno de los mejores tours que he podido contratar'),
            preserve_default=False,
        ),
    ]
