# Generated by Django 4.2.9 on 2024-01-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0004_enlacepago_descripcionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacepago',
            name='cantidad',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
