# Generated by Django 4.2.9 on 2024-01-23 22:55

import Transacciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0005_enlacepago_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacepago',
            name='imagen',
            field=models.ImageField(default=222, upload_to=Transacciones.models.upload_to_transactions),
            preserve_default=False,
        ),
    ]
