# Generated by Django 4.2.9 on 2024-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0006_enlacepago_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='imagen',
            field=models.CharField(max_length=250),
        ),
    ]
