# Generated by Django 4.2.9 on 2024-01-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0008_alter_enlacepago_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlacepago',
            old_name='imagen',
            new_name='imagenProducto',
        ),
    ]
