# Generated by Django 4.2.9 on 2024-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0010_enlacepago_idenlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='imagenProducto',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
