# Generated by Django 4.2.9 on 2024-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0010_enlacepago_idenlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='idEnlace',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
