# Generated by Django 4.2.9 on 2024-01-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0011_alter_enlacepago_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlacepago',
            name='imagenProducto',
        ),
    ]
