# Generated by Django 4.2.9 on 2024-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0012_remove_enlacepago_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacepago',
            name='imagenProducto',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
