# Generated by Django 4.2.9 on 2024-01-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0011_alter_enlacepago_idenlace'),
        ('Transacciones', '0013_enlacepago_imagenproducto'),
    ]

    operations = [
    ]
