# Generated by Django 4.2.9 on 2024-01-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0014_merge_20240130_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='idEnlace',
            field=models.CharField(max_length=150),
        ),
    ]
