# Generated by Django 4.2.9 on 2024-02-04 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0015_alter_enlacepago_idenlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='descripcionProducto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
