# Generated by Django 4.2.9 on 2024-04-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0024_reserva_estado_reserva'),
        ('Transacciones', '0016_alter_enlacepago_descripcionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlace_pago_set', to='Tours.reserva'),
        ),
    ]
