# Generated by Django 4.2.9 on 2024-05-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0017_alter_enlacepago_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnlacePago',
        ),
    ]
