# Generated by Django 4.2.9 on 2024-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia_en_inventario',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
