# Generated by Django 4.2.9 on 2024-01-16 16:36

import Nosotros.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to=Nosotros.models.upload_to_nosotros)),
                ('texto_boton', models.CharField(max_length=50)),
                ('url_boton', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Nosotros_Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oferta', models.CharField(max_length=50)),
                ('porcentaje_descuento', models.CharField(max_length=50)),
                ('servicio_descuento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('detalle_1', models.CharField(max_length=50)),
                ('detalle_2', models.CharField(max_length=50)),
                ('detalle_3', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_titulo', models.CharField(max_length=50)),
                ('servicio_descripcion', models.TextField()),
                ('Servicio_icono', models.ImageField(upload_to=Nosotros.models.upload_to_servicios)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oferta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nosotros.nosotros_oferta')),
            ],
        ),
    ]
