# Generated by Django 4.2.9 on 2024-01-19 22:54

import Nosotros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='imagen_pequeña_1',
            field=models.ImageField(default=1, upload_to=Nosotros.models.upload_to_nosotros),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imagen_pequeña_2',
            field=models.ImageField(default=1, upload_to=Nosotros.models.upload_to_nosotros),
            preserve_default=False,
        ),
    ]
