# Generated by Django 4.2.9 on 2024-01-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0002_nosotros_imagen_pequeña_1_nosotros_imagen_pequeña_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosotros',
            old_name='imagen_pequeña_1',
            new_name='imagen_pequena_1',
        ),
        migrations.RenameField(
            model_name='nosotros',
            old_name='imagen_pequeña_2',
            new_name='imagen_pequena_2',
        ),
    ]
