# Generated by Django 4.2.9 on 2024-02-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0003_rename_imagen_pequeña_1_nosotros_imagen_pequena_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosotros_servicios',
            old_name='Servicio_icono',
            new_name='servicio_icono',
        ),
    ]
