# Generated by Django 4.2.9 on 2024-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0004_rename_servicio_icono_nosotros_servicios_servicio_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='imagen_pequena_1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imagen_pequena_2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nosotros_servicios',
            name='icono_url',
            field=models.URLField(blank=True),
        ),
    ]
