# Generated by Django 4.2.9 on 2024-02-03 15:26

import Nosotros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0005_nosotros_imagen_pequena_1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros_oferta',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nosotros_oferta',
            name='oferta_imagen',
            field=models.ImageField(default=1, upload_to=Nosotros.models.upload_to_servicios),
            preserve_default=False,
        ),
    ]
