# Generated by Django 4.2.9 on 2024-02-03 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0006_nosotros_oferta_imagen_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros_oferta',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
