# Generated by Django 4.2.9 on 2024-02-04 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0007_alter_nosotros_oferta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nosotros_servicios',
            name='servicio_descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
