# Generated by Django 4.2.9 on 2024-02-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0008_alter_nosotros_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros_oferta',
            name='estado_oferta',
            field=models.BooleanField(default=True),
        ),
    ]
