# Generated by Django 4.2.9 on 2024-02-13 19:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0009_nosotros_oferta_estado_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', ckeditor.fields.RichTextField()),
                ('condiciones', ckeditor.fields.RichTextField()),
                ('politicas', ckeditor.fields.RichTextField()),
                ('mision', ckeditor.fields.RichTextField()),
                ('vision', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
