# Generated by Django 4.2.9 on 2024-06-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion3DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.CharField(max_length=150)),
                ('mesVencimiento', models.CharField(max_length=50)),
                ('anioVencimiento', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('monto', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_acceso', to='Internet.accesos')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion3DS_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTransaccion', models.CharField(max_length=150)),
                ('esReal', models.BooleanField(default=True)),
                ('urlCompletarPago3Ds', models.URLField(max_length=500)),
                ('monto', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('transaccion3ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_respuesta_set', to='Internet.transaccion3ds')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionCompra3DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_transaccion3ds_set', to='Internet.accesos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_transaccion3ds_set', to='Internet.clientes')),
                ('transaccion3ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_set', to='Internet.transaccion3ds')),
                ('transaccion3ds_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_respuesta_set', to='Internet.transaccion3ds_respuesta')),
            ],
        ),
    ]
