# Generated by Django 4.2.9 on 2024-06-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internet', '0002_transaccion3ds_transaccion3ds_respuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('puerto', models.CharField(max_length=50)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tipos',
            name='nombre_perfil',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipos',
            name='nombre_servidor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
