# Generated by Django 4.2.9 on 2026-06-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cajas', '0001_initial'),
        ('Clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo (equipo fuera)'), ('parcial', 'Devuelto parcial'), ('devuelto', 'Devuelto')], default='activo', max_length=20)),
                ('tipo_pago', models.CharField(default='efectivo', max_length=20)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cajas.cajas')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, help_text='Ej. Tienda, Colchoneta, Hamaca', max_length=60)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='Tarifa por unidad (IVA incluido)', max_digits=10)),
                ('deposito_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alquileres')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo de alquiler',
                'verbose_name_plural': 'Artículos de alquiler',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlquilerDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('tarifa_unitaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Alquileres.alquiler')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Alquileres.articuloalquiler')),
            ],
        ),
    ]
