# Generated by Django 4.2.9 on 2024-03-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caja', models.CharField(max_length=50)),
                ('nombre_caja', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('en_proceso', 'En proceso')], max_length=20)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_gastos_devoluciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informacion_auditoria', models.TextField()),
                ('comentarios_notas', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('cierre', 'Cierre'), ('apertura', 'Apertura'), ('devuelta', 'Devolución')], max_length=50)),
                ('efectivo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=100)),
                ('numero_remesa', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_remesa', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_remesado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cajas.cajas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo_cierre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_cierre', models.DateTimeField()),
                ('comentarios_notas', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='Cajas.cajas')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('comentarios_notas', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='Cajas.cajas')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
